### ISSUE TITLE
CustomView not only text?

### ISSUE THREAD

**Issue by EmilAlipiev** [jzeferino/Xamarin.Android.Tooltips#14]
Is it possible to implement a custom view instead of only text? i would like to display an icon with text. Would this be possible?

**Comment by jzeferino** [comment]
This is just a binding, please open the issue [here](https://github.com/tomergoldst/tooltips/issues)

**Comment by EmilAlipiev** [comment]
i saw after that he has another repo for custom view https://github.com/tomergoldst/hoverview
quick question, did you generate jar file yourself or it was exist somewhere. i couldnt find on his release. when i tried to generate using gradlew.bat file, it returns me some certificate error. not sure if you had it also.

**Comment by jzeferino** [comment]
That repo probably didn't exist at the time I binded this one.\

I build the project and use the generated .jar.
