### ISSUE TITLE
what's the minimum android version on which tooltip package supports ?

### ISSUE THREAD

**Issue by suryadotnet** [jzeferino/Xamarin.Android.Tooltips#16]
what's the minimum android version on which tooltip package supports?

**Comment by jzeferino** [comment]
orignal libray was compiled with min api [14](https://github.com/tomergoldst/tooltips/blob/fdf60bd85b9d4adf2ac9ff59fb4d130085cab4a7/app/build.gradle#L9). the binding is targeting api 25 but it doesn't matter.

**Comment by SuryaDotNet** [comment]
Thanks for your reply @jzeferino. As per your reply, it should work in all the devices who have Android 4.0 or higher versions. right?

**Comment by suryadotnet** [comment]
Thanks for your reply @jzeferino. As per your reply, it should work in all the devices that have Android 4.0 or higher versions. right?

**Comment by jzeferino** [comment]
yes.
