### ISSUE TITLE
Use in Xamarin Forms

### ISSUE THREAD

**Issue by wanderson-ra** [jzeferino/Xamarin.Android.Tooltips#9]
Is there any way to use in Xamarin Forms with custom renderers?
If so can you give me a hand?

**Comment by jzeferino** [comment]
I will try to make a working sample for you. Just need to get some free time.

**Comment by wanderson-ra** [comment]
All right, I'll be waiting. Thank you!

**Comment by jzeferino** [comment]
Be aware that this will only work for Android not for iOS.

**Comment by wanderson-ra** [comment]
Okay, for IOS I'll do another type of implementation, if you can only help me with Android I'm already grateful.

**Comment by wanderson-ra** [comment]
I tried to make an implementation using custon render in xamarin forms, but without success.

**Comment by jzeferino** [comment]
Share the repository with me so I can take a look.

**Comment by wanderson-ra** [comment]
Unfortunately the entire solution can not put git. However it follows the Custon Render's OnElementPropertyChanged method code. Unfortunately it does not produce results. 

```
[assembly: ExportRenderer(typeof(TooltipLayout), typeof(TooltipLayoutRenderer))]
namespace Tradutor.Libras.Mobile.Droid.Controls
{
    public class TooltipLayoutRenderer : IconImageRenderer,ToolTipsManager.ITipListener
    {
        private readonly Context _context;
        private readonly ToolTipsManager _toolTipsManager;
        public TooltipLayoutRenderer(Context context)
        {
            _context = context;
            _toolTipsManager = new ToolTipsManager(this);
        }

        public void OnTipDismissed(View view, int anchorViewId, bool byUser)
        {
			
       }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);

            if (Element == null)
                return;

            if (Control == null)
                return;

            if (e.PropertyName != TooltipLayout.EnableTooltipProperty.PropertyName) return;

            var tooltipLayout = (TooltipLayout)Element;

            if (!tooltipLayout.EnableTooltip) return;          



            SetNativeControl(Control);
            var builder = new ToolTip.Builder(_context, Control, ViewGroup, "Hello", ToolTip.PositionRightTo);
            builder.SetAlign(ToolTip.PositionRightTo);

            _toolTipsManager.Show(builder.Build());
        }
    }
}


```

**Comment by olezhko** [comment]
I`m also intrested in this question. Perhaps, we have problems with ViewGroup in Builder

**Comment by EmilAlipiev** [comment]
you can try my xamarin.forms nuget package. it works for android, ios and uwp
https://www.nuget.org/packages/Plugin.myToolTip/
There is a sample project also in the repo
https://github.com/EmilAlipiev/myToolTip
